version: '3.8'

services:  
    mariadb:
        image: mariadb:10.6.5
        container_name: fatboar-db
        restart: always        
        env_file:
            - .env.docker
        ports:
            - 3306
        volumes:
            - mariadb:/var/lib/mysql
        networks: 
            - mariadb

    adminer:
        image: adminer
        restart: always
        env_file:
            - .env.docker
        ports:
            - 8082:8080
        networks:
            - mariadb
        depends_on:
            - mariadb

    api:
        image: node:14
        working_dir: /usr/src/app/fatboar-api
        container_name: fatboar-api
        env_file:
            - .env.docker
        ports:
            - "3000:3000"
        depends_on: 
            - mariadb
        volumes:
            - ./fatboar-api:/usr/src/app/fatboar-api
            - ./server.key:/usr/src/app/server.key
            - ./server.cert:/usr/src/app/server.cert
        networks:
            - api
            - mariadb
        command: sh -c "npm install
         && npm install -g @nestjs/cli ts-node \
         && npm run ${API_NPM_RUN}"

    front:
        image: node:14
        working_dir: /usr/src/app/fatboar-concours
        container_name: fatboar-concours
        env_file:
            - .env.docker
        ports:
            - "${FRONT_PORT}:8080"
        volumes:
            - ./fatboar-concours:/usr/src/app/fatboar-concours
            - ./server.key:/usr/src/app/server.key
            - ./server.cert:/usr/src/app/server.cert
        networks:
            - api 
        command: sh -c "npm i && npm run ${FRONT_NPM_RUN}" 

    telegraf:
        image: telegraf:1.21
        container_name: telegraf
        restart: always
        env_file:
            - .env.docker
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /sys:/rootfs/sys:ro
            - /proc:/rootfs/proc:ro
            - /etc:/rootfs/etc:ro
        ports:
            - 8125:8125

networks:
    api:
    mariadb:

volumes: 
    mariadb:
