pipeline {
    agent {
        docker { image 'blazemeter/taurus' }
    }
    stages {
        stage('install bzt') {
            sh 'pip install bzt'
        }
        stage('test perf') {
            bzt "fatboar-api/test/perf.jmx"
        } 
    }
} 
