pipeline {
    agent {
        docker { image 'nikolaik/python-nodejs:python3.9-nodejs16' }
    }
    stages {
        stage('perf') {
            steps {
                sh 'pip install Cmake bzt && bzt "fatboar-api/test/perf.jmx"'
            }
        } 
    }
} 
