name: CI/CD main

on:
  push:
    branches: [ main ]

jobs:
  tests:
    uses: MaeBzh/fatboar-concours/.github/workflows/jenkins.yml@main

  release:
    uses: MaeBzh/fatboar-concours/.github/workflows/release.yml@main
    if: ${{ github.ref == 'refs/heads/main' && contains(join(needs.tests.result, ','), 'success') }}
    needs: tests

 deploy: 
    uses: MaeBzh/fatboar-concours/.github/workflows/deploy.yml@main
    needs: release
    with:
      branchName: main
    secrets:
      sshUsername: ${{ secrets.PROD_SSH_USERNAME }}
      sshKey: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
      sshHost: ${{ secrets.PROD_SSH_HOST }}
      sshPort: ${{ secrets.PROD_SSH_PORT }}
   