name: CI/CD main

on:
  push:
    branches: [ main ]

jobs:
  tests:
    uses: ./.github/workflows/jenkins.yml@main
    secrets: inherit

  release:
    uses: ./.github/workflows/release.yml@main
    if: ${{ github.ref == 'refs/heads/main' && contains(join(needs.tests.result, ','), 'success') }}
    needs: tests
    secrets: inherit

 deploy: 
    uses: ./.github/workflows/deploy.yml@main

    needs: release
    with:
      branchName: main
    secrets:
      SSH_USERNAME: ${{ secrets.PROD_SSH_USERNAME }}
      SSH_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
      SSH_PORT: ${{ secrets.PROD_SSH_PORT }}

   