name: CI/CD main

on:
  push:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/jenkins.yml
    secrets: 
      JENKINS_URL: ${{ secrets.JENKINS_URL }}
      JENKINS_USER: ${{ secrets.JENKINS_USER }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}

  release:
    uses: ./.github/workflows/release.yml
    if: ${{ github.ref == 'refs/heads/main' && contains(join(needs.tests.result, ','), 'success') }}
    needs: tests
    secrets: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy: 
    uses: ./.github/workflows/deploy.yml
    needs: release
    secrets:
      SSH_USERNAME: ${{ secrets.PROD_SSH_USERNAME }}
      SSH_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
      SSH_PORT: ${{ secrets.PROD_SSH_PORT }}

   