name: CI/CD preprod

on:
  push:
    branches: [ preprod ]

jobs:
  tests:
    uses: MaeBzh/fatboar-concours/.github/workflows/jenkins.yml

  deploy:
    needs: tests
    uses: MaeBzh/fatboar-concours/.github/workflows/deploy.yml
    if: ${{ github.ref == 'refs/heads/preprod' && contains(join(needs.tests.result, ','), 'success') }}
    secrets:
      sshUsername: ${{ secrets.PREPROD_SSH_USERNAME }}
      sshKey: ${{ secrets.PREPROD_SSH_PRIVATE_KEY }}
      sshHost: ${{ secrets.PREPROD_SSH_HOST }}
      sshPort: ${{ secrets.PREPROD_SSH_PORT }}
