name: CI/CD preprod

on:
  push:
    branches: [ preprod ]

jobs:
  tests:
    uses: ./.github/workflows/jenkins.yml@main
    secrets: inherit

  deploy:
    needs: tests
    uses: ./.github/workflows/deploy.yml@main
    if: ${{ github.ref == 'refs/heads/preprod' && contains(join(needs.tests.result, ','), 'success') }}
    secrets:
      SSH_USERNAME: ${{ secrets.PREPROD_SSH_USERNAME }}
      SSH_KEY: ${{ secrets.PREPROD_SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.PREPROD_SSH_HOST }}
      SSH_PORT: ${{ secrets.PREPROD_SSH_PORT }}
