 release:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ github.ref == 'refs/heads/main' && contains(join(needs.tests.result, ','), 'success') }}
    steps:
      - name: Create a release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor # for a major release or a patch, add "major" or "patch" in the commit message
          tag_prefix: ""