name: CI tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop, preprod ]

jobs:
  tests:
    uses: MaeBzh/fatboar-concours/.github/workflows/jenkins.yml
  quality:
    uses: MaeBzh/fatboar-concours/.github/workflows/sonarqube.yml
  