name: CI tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop, preprod]

jobs:
  tests:
    uses: ./.github/workflows/jenkins.yml@main
    secrets: inherit
  quality:
    uses: ./.github/workflows/sonarqube.yml@main
    secrets: inherit
